SELECT * FROM PLAYER

INSERT INTO PLAYER(PLAYER_NO, PLAYER_NM, PLAYER_SALARY, PLAYER_PASSWORD)
VALUES()

SELECT * FROM HITTER;

ALTER TABLE HITTER ADD PLAYER_BA NUMBER;

SELECT * FROM PITCHER;

ALTER TABLE HITTER DROP (PLAYER_BA);

ALTER TABLE PITCHER DROP (PLY_ERA);

COMMIT;

DELETE FROM PLAYER 
WHERE PLAYER_NO = 1;

INSERT INTO HITTER VALUES(99, 542, 170, 60);

ALTER TABLE PLAYER DROP CONSTRAINT SYS_C008474;

DELETE FROM HITTER
WHERE PLAYER_NO =0;

ALTER TABLE HITTER RENAME COLUMN PLAYER_BA TO PLAYER_AB;

SELECT PLAYER_NO AS 번호, PLAYER_AB AS 타수, PLAYER_HIT AS 안타, PLAYER_HOME AS 홈런, ROUND( PLAYER_HIT / PLAYER_AB ,  3) AS 타율 
FROM HITTER


INSERT INTO PITCHER VALUES(?, ?, ?, ?, ?);

SELECT PLAYER_NO, PLAYE_VIC, PLA_LOSE, PLY_INN, PLA_ER, ROUND( PLA_ER * 9 / PLY_INN, 2)
FROM PITCHER
WHERE PLAYER_NO = ?

SELECT * FROM PLAYER

UPDATE PLAYER SET PLAYER_DIV = 'HIT'
WHERE PLAYER_NO = 99

UPDATE PLAYER SET PLAYER_ENROLL = 2017
WHERE PLAYER_NO = 54;

COMMIT;
SELECT * FROM PLAYER;

SELECT * FROM HITTER;

SELECT * FROM PITCHER;

INSERT INTO PLAYER VALUES(17, '애런 분', NULL, 2018, DEFAULT, 'MN17', 'M');
	

UPDATE PLAYER SET
PLAYER_DIV = 'HIT'
WHERE PLAYER_NO = 1;

DELETE FROM PLAYER
WHERE PLAYER_NM ='1';
-- 투수 전체 조회

SELECT PLAYER_NO, PLAYER_NM, PLAYE_VIC, PLA_LOSE, PLY_INN, ROUND((PLA_ER * 9 / PLY_INN), 2)
FROM PLAYER
JOIN PITCHER USING(PLAYER_NO);

INSERT INTO PLAYER VALUES(1, '테스트', 1500, DEFAULT, DEFAULT, 'P1', 'PIT');

INSERT INTO HITTER VALUES(1, 10, 2, 1);

UPDATE PITCHER SET 
PLAYE_VIC = PLAYE_VIC + 1,
PLA_LOSE = PLA_LOSE + 1,
PLY_INN = PLY_INN + 1,
PLA_ER = PLA_ER + 1
WHERE PLAYER_NO = 2;

SELECT * FROM PITCHER
WHERE PLAYER_NO =2;

ALTER TABLE PLAYER MODIFY PLAYER_DIV VARCHAR2(30);

UPDATE PLAYER SET PLAYER_DIV = 'MANAGER'
WHERE PLAYER_NM = '애런 분';


SELECT PLAYER_NO, PLAYER_NM, PLAYER_AB, PLAYER_HIT, PLAYER_HOME, ROUND((PLAYER_HIT / PLAYER_AB), 3)
FROM PLAYER
JOIN HITTER USING(PLAYER_NO);


SELECT * FROM HITTER
WHERE PLAYER_NO =1;

UPDATE HITTER SET
PLAYER_AB = PLAYER_AB + 10,
PLAYER_HIT = PLAYER_HIT + 2,
PLAYER_HOME = PLAYER_HOME + 1
WHERE PLAYER_NO = 1

SELECT COUNT(*)
FROM PLAYER
WHERE PLAYER_TEAM = 'NY'
AND PLAYER_NO = ?

DELETE FROM PLAYER
WHERE PLAYER_NO = 1;


SELECT PLAYER_NO, PLAYER_NM, PLAYER_SALARY, PLAYER_ENROLL, PLAYER_DIV, SUBSTR(PLAYER_PASSWORD, 1, 2)||'**' 
FROM PLAYER
WHERE PLAYER_TEAM = 'NY'

ALTER TABLE PLAYER ADD CONSTRAINT PL_PK PRIMARY KEY(PLAYER_NO);
