SELECT * FROM PLAYER

INSERT INTO PLAYER(PLAYER_NO, PLAYER_NM, PLAYER_SALARY, PLAYER_PASSWORD)
VALUES()

SELECT * FROM HITTER;

ALTER TABLE HITTER ADD PLAYER_BA NUMBER;

SELECT * FROM PITCHER;

ALTER TABLE HITTER DROP (PLAYER_BA);

ALTER TABLE PITCHER DROP (PLY_ERA);

COMMIT;

DELETE FROM PLAYER 
WHERE PLAYER_NO = 1;

INSERT INTO HITTER VALUES(99, 542, 170, 60);

ALTER TABLE PLAYER DROP CONSTRAINT SYS_C008474;

DELETE FROM HITTER
WHERE PLAYER_NO =0;

ALTER TABLE HITTER RENAME COLUMN PLAYER_BA TO PLAYER_AB;

SELECT PLAYER_NO AS 번호, PLAYER_AB AS 타수, PLAYER_HIT AS 안타, PLAYER_HOME AS 홈런, ROUND( PLAYER_HIT / PLAYER_AB ,  3) AS 타율 
FROM HITTER


INSERT INTO PITCHER VALUES(?, ?, ?, ?, ?);

SELECT PLAYER_NO, PLAYE_VIC, PLA_LOSE, PLY_INN, PLA_ER, ROUND( PLA_ER * 9 / PLY_INN, 2)
FROM PITCHER
WHERE PLAYER_NO = ?

SELECT * FROM PLAYER

UPDATE PLAYER SET PLAYER_DIV = 'HIT'
WHERE PLAYER_NO = 99

UPDATE PLAYER SET PLAYER_ENROLL = 2017
WHERE PLAYER_NO = 54;

ALTER TABLE PLAYER ADD (PLAYER_DIV CHAR(3)); 


UPDATE PLAYER SET PLAYER_TEAM = 'NY'
WHERE PLAYER_NO = 1;