-- 1
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

-- 2
SELECT CAPACITY||'명입니다'"학과별 정원"
FROM TB_DEPARTMENT
/*
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY ||'명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;
*/

--3
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'Y'
AND DEPARTMENT_NO = '001'
AND SUBSTR(STUDENT_SSN, 8, 1) = '2';

--4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A513___' AND STUDENT_NAME LIKE '_경_' AND STUDENT_NO > 'A513075'
ORDER BY STUDENT_NAME DESC;
	
--5
SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30

--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT 

--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'N' AND ENTRANCE_DATE BETWEEN'2002-01-01'AND '2002-12-31' 
AND STUDENT_ADDRESS LIKE '전주%';


SQL2

--1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3
SELECT PROFESSOR_NAME 교수이름, 100-(SUBSTR( PROFESSOR_SSN, 1, 2)) + 22 나이
FROM TB_PROFESSOR
WHERE SUBSTR( PROFESSOR_SSN, 8, 1) = '1';  
/*
SELECT PROFESSOR_NAME, 
FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE( 19 || SUBSTR(PROFESSROR_SSN, 1, 6)))/12 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
ORDER BY 나이;
*/

--4
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) 이름
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE, 1, 4) - (SUBSTR(STUDENT_SSN, 1, 2) + 1900) = 19;
/*
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) 
    - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) > 19;
*/

--6
SELECT TO_CHAR(TO_DATE('20201225'), 'DY') FROM DUAL;

--7
TO_DATE('99/10/11', 'YY/MM/DD') -- 2099/10/11
TO_DATE('49/10/11', 'YY/MM/DD') -- 2049/10/11
TO_DATE('99/10/11', 'RR/MM/DD') -- 1999/10/11
TO_DATE('49/10/11', 'RR/MM/DD') -- 2049/10/11

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE <'2000-01-01';


--9
SELECT ROUND( AVG(POINT), 1)평균
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

--10(?)
SELECT DISTINCT DEPARTMENT_NO 학과번호, COUNT(DEPARTMENT_NO) "학생수(명)"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO )
GROUP BY DEPARTMENT_NO 
ORDER BY 1;


--11
SELECT COUNT(*) 
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT SUBSTR(TERM_NO, 1, 4)년도, ROUND(AVG(POINT), 1)"년도별 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;
/*
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND( AVG(POINT), 1) "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도;
*/


--13
SELECT DEPARTMENT_NO, COUNT(ABSENCE_YN)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 1;
/*
SELECT DEPARTMENT_NO 학과코드명,
  SUM( DECODE(ABSENCE_YN, 'Y', 1, 0) ) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO


SELECT DEPARTMENT_NO 학과코드명, 
 COUNT( DECODE(ABSENCE_YN, 'Y', 1, 0) ) "휴학생 수"
FROM TB_STUDENT
ORDER BY DEPARTMENT_NO
*/

--14(?)
/* SELECT STUDENT_NAME 동일이름, COUNT(*) "동명인 수 "
   FROM TB_STUDENT
   GROUP BY STUDENT_NAME  
   HAVING COUNT(*) >=2
   ORDER BY 1;
*/

--15
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, POINT
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO = 'A112113';

/*
 SELECT * FROM TB_GRADE;
 
 SELECT NVL (SUBSTR(TERM_NO, 1, 4) , ' ') 년도, 
        NVL (SUBSTR(TERM_NO, 5, 2) , ' ') 학기,
        ROUND( AVG(POINT), 1) 평점 
 FROM TB_GRADE;
 WHERE STUDENT_NO = 'A112113'
 GROUP BY ROLLUP( SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
 ORDER BY SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2)
 */


